
import 'package:adrenture/models/marcas.dart';

void Main() {
  List<Brand> marcas = [
    Brand(id: 2, nomeMarca: 'Audi'),
    Brand(id: 3, nomeMarca: 'Mercedes-Benz'),
    Brand(id: 1, nomeMarca: 'BMW'),
    Brand(id: 4, nomeMarca: 'Toyota'),
    Brand(id: 5, nomeMarca: 'Honda'),
    Brand(id: 6, nomeMarca: 'Ford'),
    Brand(id: 7, nomeMarca: 'Chevrolet'),
    Brand(id: 8, nomeMarca: 'Volkswagen'),
    Brand(id: 9, nomeMarca: 'Hyundai'),
    Brand(id: 10, nomeMarca: 'Nissan'),
    Brand(id: 11, nomeMarca: 'Kia'),
    Brand(id: 12, nomeMarca: 'Peugeot'),
    Brand(id: 13, nomeMarca: 'Fiat'),
    Brand(id: 14, nomeMarca: 'Renault'),
    Brand(id: 15, nomeMarca: 'Mazda'),
    Brand(id: 16, nomeMarca: 'Subaru'),
    Brand(id: 17, nomeMarca: 'Jaguar'),
    Brand(id: 18, nomeMarca: 'Land Rover'),
    Brand(id: 19, nomeMarca: 'Volvo'),
    Brand(id: 20, nomeMarca: 'Lexus'),
    Brand(id: 21, nomeMarca: 'Acura'),
    Brand(id: 22, nomeMarca: 'Infiniti'),
    Brand(id: 23, nomeMarca: 'Mitsubishi'),
    Brand(id: 24, nomeMarca: 'Suzuki'),
    Brand(id: 25, nomeMarca: 'Porsche'),
    Brand(id: 26, nomeMarca: 'Ferrari'),
    Brand(id: 27, nomeMarca: 'Lamborghini'),
    Brand(id: 28, nomeMarca: 'Maserati'),
    Brand(id: 29, nomeMarca: 'Alfa Romeo'),
    Brand(id: 30, nomeMarca: 'Bentley'),
    Brand(id: 31, nomeMarca: 'Rolls-Royce'),
    Brand(id: 32, nomeMarca: 'Aston Martin'),
    Brand(id: 33, nomeMarca: 'Bugatti'),
    Brand(id: 34, nomeMarca: 'Tesla'),
    Brand(id: 35, nomeMarca: 'McLaren'),
    Brand(id: 36, nomeMarca: 'Pagani'),
    Brand(id: 37, nomeMarca: 'Koenigsegg'),
    Brand(id: 38, nomeMarca: 'Genesis'),
    Brand(id: 39, nomeMarca: 'Chrysler'),
    Brand(id: 40, nomeMarca: 'Dodge'),
    Brand(id: 41, nomeMarca: 'Jeep'),
    Brand(id: 42, nomeMarca: 'Ram'),
    Brand(id: 43, nomeMarca: 'Buick'),
    Brand(id: 44, nomeMarca: 'Cadillac'),
    Brand(id: 45, nomeMarca: 'GMC'),
    Brand(id: 46, nomeMarca: 'Lincoln'),
    Brand(id: 47, nomeMarca: 'Mini'),
    Brand(id: 48, nomeMarca: 'Smart'),
    Brand(id: 49, nomeMarca: 'Saab'),
    Brand(id: 50, nomeMarca: 'Skoda'),
    Brand(id: 51, nomeMarca: 'Seat'),
    Brand(id: 52, nomeMarca: 'Lancia'),
    Brand(id: 53, nomeMarca: 'Citroën'),
    Brand(id: 54, nomeMarca: 'Opel'),
    Brand(id: 55, nomeMarca: 'Vauxhall'),
    Brand(id: 56, nomeMarca: 'DS Automobiles'),
    Brand(id: 57, nomeMarca: 'Abarth'),
    Brand(id: 58, nomeMarca: 'Dacia'),
    Brand(id: 59, nomeMarca: 'Holden'),
    Brand(id: 60, nomeMarca: 'Proton'),
    Brand(id: 61, nomeMarca: 'Perodua'),
    Brand(id: 62, nomeMarca: 'Chery'),
    Brand(id: 63, nomeMarca: 'Great Wall'),
    Brand(id: 64, nomeMarca: 'Geely'),
    Brand(id: 65, nomeMarca: 'Haval'),
    Brand(id: 66, nomeMarca: 'Roewe'),
    Brand(id: 67, nomeMarca: 'MG'),
    Brand(id: 68, nomeMarca: 'BYD'),
    Brand(id: 69, nomeMarca: 'Lifan'),
    Brand(id: 70, nomeMarca: 'Foton'),
    Brand(id: 71, nomeMarca: 'Mahindra'),
    Brand(id: 72, nomeMarca: 'Tata'),
    Brand(id: 73, nomeMarca: 'Maruti Suzuki'),
    Brand(id: 74, nomeMarca: 'Force Motors'),
    Brand(id: 75, nomeMarca: 'Ashok Leyland'),
    Brand(id: 76, nomeMarca: 'Premier'),
    Brand(id: 77, nomeMarca: 'Hindustan Motors'),
    Brand(id: 78, nomeMarca: 'TVS'),
    Brand(id: 79, nomeMarca: 'Hero'),
    Brand(id: 80, nomeMarca: 'Bajaj'),
    Brand(id: 81, nomeMarca: 'Piaggio'),
    Brand(id: 82, nomeMarca: 'Aprilia'),
    Brand(id: 83, nomeMarca: 'Ducati'),
    Brand(id: 84, nomeMarca: 'MV Agusta'),
    Brand(id: 85, nomeMarca: 'Benelli'),
    Brand(id: 86, nomeMarca: 'Royal Enfield'),
    Brand(id: 87, nomeMarca: 'Triumph'),
    Brand(id: 88, nomeMarca: 'Norton'),
    Brand(id: 89, nomeMarca: 'BSA'),
    Brand(id: 90, nomeMarca: 'Ariel'),
    Brand(id: 91, nomeMarca: 'Caterham'),
    Brand(id: 92, nomeMarca: 'Morgan'),
    Brand(id: 93, nomeMarca: 'Lotus'),
    Brand(id: 94, nomeMarca: 'Radical'),
    Brand(id: 95, nomeMarca: 'Ginetta'),
    Brand(id: 96, nomeMarca: 'Westfield'),
    Brand(id: 97, nomeMarca: 'Noble'),
    Brand(id: 98, nomeMarca: 'Ultima'),
    Brand(id: 99, nomeMarca: 'Zenos'),
    Brand(id: 100, nomeMarca: 'BAC'),
    Brand(id: 101, nomeMarca: 'Rezvani'),
    Brand(id: 102, nomeMarca: 'Lucid'),
    Brand(id: 103, nomeMarca: 'Rivian'),
    Brand(id: 104, nomeMarca: 'Faraday Future'),
    Brand(id: 105, nomeMarca: 'Fisker'),
    Brand(id: 106, nomeMarca: 'Aptera'),
    Brand(id: 107, nomeMarca: 'Arcimoto'),
    Brand(id: 108, nomeMarca: 'Lordstown'),
    Brand(id: 109, nomeMarca: 'Nikola'),
    Brand(id: 110, nomeMarca: 'Elio Motors'),
    Brand(id: 111, nomeMarca: 'Scion'),
    Brand(id: 112, nomeMarca: 'Saturn'),
    Brand(id: 113, nomeMarca: 'Oldsmobile'),
    Brand(id: 114, nomeMarca: 'Pontiac'),
    Brand(id: 115, nomeMarca: 'Plymouth'),
    Brand(id: 116, nomeMarca: 'AMC'),
    Brand(id: 117, nomeMarca: 'Studebaker'),
    Brand(id: 118, nomeMarca: 'Packard'),
    Brand(id: 119, nomeMarca: 'DeSoto'),
    Brand(id: 120, nomeMarca: 'Imperial'),
    Brand(id: 121, nomeMarca: 'LaSalle'),
    Brand(id: 122, nomeMarca: 'Hudson'),
    Brand(id: 123, nomeMarca: 'Nash'),
    Brand(id: 124, nomeMarca: 'Willys'),
    Brand(id: 125, nomeMarca: 'Duesenberg'),
    Brand(id: 126, nomeMarca: 'Cord'),
    Brand(id: 127, nomeMarca: 'Auburn'),
    Brand(id: 128, nomeMarca: 'Tucker'),
    Brand(id: 129, nomeMarca: 'Panoz'),
    Brand(id: 130, nomeMarca: 'Vector'),
    Brand(id: 131, nomeMarca: 'Saleen'),
    Brand(id: 132, nomeMarca: 'Mosler'),
    Brand(id: 133, nomeMarca: 'Callaway'),
    Brand(id: 134, nomeMarca: 'Rossion'),
    Brand(id: 135, nomeMarca: 'Spyker'),
    Brand(id: 136, nomeMarca: 'Gumpert'),
    Brand(id: 137, nomeMarca: 'Artega'),
    Brand(id: 138, nomeMarca: 'Wiesmann'),
    Brand(id: 139, nomeMarca: 'Melkus'),
    Brand(id: 140, nomeMarca: 'Isdera'),
    Brand(id: 141, nomeMarca: 'Trabant'),
    Brand(id: 142, nomeMarca: 'Wartburg'),
    Brand(id: 143, nomeMarca: 'ARO'),
    Brand(id: 144, nomeMarca: 'Dacia'),
    Brand(id: 145, nomeMarca: 'Zastava'),
    Brand(id: 146, nomeMarca: 'Yugo'),
    Brand(id: 147, nomeMarca: 'GAZ'),
    Brand(id: 148, nomeMarca: 'UAZ'),
    Brand(id: 149, nomeMarca: 'Lada'),
    Brand(id: 150, nomeMarca: 'Volga'),
    Brand(id: 151, nomeMarca: 'Moskvitch'),
    Brand(id: 152, nomeMarca: 'ZAZ'),
    Brand(id: 153, nomeMarca: 'Kamaz'),
    Brand(id: 154, nomeMarca: 'MAZ'),
    Brand(id: 155, nomeMarca: 'BelAZ'),
    Brand(id: 156, nomeMarca: 'KrAZ'),
    Brand(id: 157, nomeMarca: 'LiAZ'),
    Brand(id: 158, nomeMarca: 'PAZ'),
    Brand(id: 159, nomeMarca: 'Ikarus'),
    Brand(id: 160, nomeMarca: 'Barkas'),
    Brand(id: 161, nomeMarca: 'IFA'),
    Brand(id: 162, nomeMarca: 'Robur'),
    Brand(id: 163, nomeMarca: 'Tatraplan'),
    Brand(id: 164, nomeMarca: 'Tatra'),
    Brand(id: 165, nomeMarca: 'Skoda'),
    Brand(id: 166, nomeMarca: 'Praga'),
    Brand(id: 167, nomeMarca: 'Aero'),
    Brand(id: 168, nomeMarca: 'Velorex'),
    Brand(id: 169, nomeMarca: 'Zaporožec'),
    Brand(id: 170, nomeMarca: 'Bogdan'),
    Brand(id: 171, nomeMarca: 'Lifan'),
    Brand(id: 172, nomeMarca: 'Changhe'),
    Brand(id: 173, nomeMarca: 'Yutong'),
    Brand(id: 174, nomeMarca: 'King Long'),
    Brand(id: 175, nomeMarca: 'Zhongtong'),
    Brand(id: 176, nomeMarca: 'Yinlong'),
    Brand(id: 177, nomeMarca: 'Xpeng'),
    Brand(id: 178, nomeMarca: 'NIO'),
    Brand(id: 179, nomeMarca: 'Li Auto'),
    Brand(id: 180, nomeMarca: 'WM Motor'),
    Brand(id: 181, nomeMarca: 'Hozon Auto'),
    Brand(id: 182, nomeMarca: 'Seres'),
    Brand(id: 183, nomeMarca: 'Leapmotor'),
    Brand(id: 184, nomeMarca: 'Enovate'),
    Brand(id: 185, nomeMarca: 'Byton'),
    Brand(id: 186, nomeMarca: 'JAC Motors'),
    Brand(id: 187, nomeMarca: 'Changan'),
    Brand(id: 188, nomeMarca: 'BAIC'),
    Brand(id: 189, nomeMarca: 'Foton'),
    Brand(id: 190, nomeMarca: 'Dongfeng'),
    Brand(id: 191, nomeMarca: 'Haima'),
    Brand(id: 192, nomeMarca: 'Zotye'),
    Brand(id: 193, nomeMarca: 'Baojun'),
    Brand(id: 194, nomeMarca: 'Hawtai'),
    Brand(id: 195, nomeMarca: 'Yema'),
    Brand(id: 196, nomeMarca: 'Soueast'),
    Brand(id: 197, nomeMarca: 'Lynk & Co'),
    Brand(id: 198, nomeMarca: 'Hongqi'),
    Brand(id: 199, nomeMarca: 'Bestune'),
    Brand(id: 200, nomeMarca: 'Daihatsu'),
    Brand(id: 201, nomeMarca: 'Isuzu'),
    Brand(id: 202, nomeMarca: 'Hino'),
    Brand(id: 203, nomeMarca: 'Datsun'),
    Brand(id: 204, nomeMarca: 'Holden'),
    Brand(id: 205, nomeMarca: 'HSV'),
    Brand(id: 206, nomeMarca: 'Proton'),
    Brand(id: 207, nomeMarca: 'Perodua'),
    Brand(id: 208, nomeMarca: 'Chery'),
    Brand(id: 209, nomeMarca: 'Geely'),
    Brand(id: 210, nomeMarca: 'JAC Motors'),
    Brand(id: 211, nomeMarca: 'Lifan'),
    Brand(id: 212, nomeMarca: 'Great Wall'),
    Brand(id: 213, nomeMarca: 'Haval'),
    Brand(id: 214, nomeMarca: 'Foton'),
    Brand(id: 215, nomeMarca: 'BYDA'),
    Brand(id: 216, nomeMarca: 'Roewe'),
    Brand(id: 217, nomeMarca: 'MG'),
    Brand(id: 218, nomeMarca: 'Zotye'),
    Brand(id: 219, nomeMarca: 'GAC'),
    Brand(id: 220, nomeMarca: 'Changan'),
    Brand(id: 221, nomeMarca: 'Dongfeng'),
    Brand(id: 222, nomeMarca: 'Haima'),
    Brand(id: 223, nomeMarca: 'Hongqi'),
    Brand(id: 224, nomeMarca: 'Bestune'),
    Brand(id: 225, nomeMarca: 'Lynk & Co'),
    Brand(id: 226, nomeMarca: 'NIO'),
    Brand(id: 227, nomeMarca: 'Xpeng'),
    Brand(id: 228, nomeMarca: 'Li Auto'),
    Brand(id: 229, nomeMarca: 'WM Motor'),
    Brand(id: 230, nomeMarca: 'Hozon Auto'),
    Brand(id: 231, nomeMarca: 'Seres'),
    Brand(id: 232, nomeMarca: 'Leapmotor'),
    Brand(id: 233, nomeMarca: 'Enovate'),
    Brand(id: 234, nomeMarca: 'Byton'),
    Brand(id: 235, nomeMarca: 'Lucid'),
    Brand(id: 236, nomeMarca: 'Rivian'),
    Brand(id: 237, nomeMarca: 'Faraday Future'),
    Brand(id: 238, nomeMarca: 'Fisker'),
    Brand(id: 239, nomeMarca: 'Aptera'),
    Brand(id: 240, nomeMarca: 'Arcimoto'),
    Brand(id: 241, nomeMarca: 'Lordstown'),
    Brand(id: 242, nomeMarca: 'Nikola'),
    Brand(id: 243, nomeMarca: 'Elio Motors'),
    Brand(id: 244, nomeMarca: 'Scion'),
    Brand(id: 245, nomeMarca: 'Saturn'),
    Brand(id: 246, nomeMarca: 'Oldsmobile'),
    Brand(id: 247, nomeMarca: 'Pontiac'),
    Brand(id: 248, nomeMarca: 'Plymouth'),
    Brand(id: 249, nomeMarca: 'AMC'),
    Brand(id: 250, nomeMarca: 'Studebaker')
  ];
}

